### ISSUE TITLE
questions about the paper

### ISSUE THREAD

**Issue by SatMa34** [greatlog/SWAHR-HumanPose#1]
In section 3.2, you introduced the scale-adaptive heatmaps, but in formula 4, you write s.t. ||i-x||<3σ ||j-y||<3σ, dose this σ refer to σ0 or σ0*s? At the first, i thought this σ refer to σ0*s, but in formula 6, you write when Hσ0 == 0, Hσ0*s=Hσ0, which means the region whose value is not zero in Hσ0 and Hσ0*s is the same, it's inconsistent with what you said "which means that the region convered by this Gaussian kernel will also become larger", so what are the facts?

**Comment by greatlog** [comment]
It is σ0. It is true that the region whose value is not zero in Hσ0 and Hσ0s is the same. However, in Hσ0, values near Gaussian kernels are about 1e-2，which in fact is much smaller than the detection threshold during testing (0.1).  It is hard to determine whether these pixels are positive or negative samples. While in Hσs, values of those pixels may be scaled up. Although the non-zero region remains unchanged, values that significant enough in Gaussian kernels may become more. 

Strictly speaking, the statement in our paper is not precise enough. It is more likely a visual description.
