### ISSUE TITLE
Is it necessary to add nn.ReLU(True) in the fuse_layers?

### ISSUE THREAD

**Issue by jin-s13** [greatlog/SWAHR-HumanPose#3]
Thanks for releasing the code.
By comparing SWAHR-HumanPose and HigherHRNet, I notice that some nn.ReLU layers are added in the fuse_layers.
I wonder what if we do not modify the original backbone network. Will it affect the final performance?

**Comment by greatlog** [comment]
No, the ReLU layer is used as a placeholder here, which acts the same as 'None' in the original version. However, since the 'None' object can not be added in a JIT model, we replace it with a ReLU layer.

**Comment by jin-s13** [comment]
Thanks for clarification.
