### ISSUE TITLE
One concern in the algorithm

### ISSUE THREAD

**Issue by AlanLuSun** [greatlog/SWAHR-HumanPose#4]
As we can see, the scale network branch directly regresses alpha = 1/s-1. When using Taylor expansion as shown in Eq. 8, in fact, due to sigma_0 has changed to s*sigma_0, the coverage of gaussian should change from 3sigma to 3*s* sigma, where is not hold in Eq. 8.

**Comment by AlanLuSun** [comment]
Eq. 8 can be found in author's paper.

**Comment by greatlog** [comment]
It can be referred to [Issue#1](https://github.com/greatlog/SWAHR-HumanPose/issues/1#issue-857715140). To be strict, the coverage of gaussian actually keeps unchanged.
