### ISSUE TITLE
Scale maps

### ISSUE THREAD

**Issue by jd0617** [greatlog/SWAHR-HumanPose#6]
May I know which part in the code produce the scale maps and which part is the element-wise operation over ground truth heatmap and scale map?

**Comment by greatlog** [comment]
The scale maps are generated [here](https://github.com/greatlog/SWAHR-HumanPose/blob/755582699faeafb89e4e00515677e0d581366012/lib/models/pose_higher_hrnet.py#L555) and [here](https://github.com/greatlog/SWAHR-HumanPose/blob/755582699faeafb89e4e00515677e0d581366012/lib/models/pose_higher_hrnet.py#L565).

The element-wise operation over GT heatmaps is [here](https://github.com/greatlog/SWAHR-HumanPose/blob/755582699faeafb89e4e00515677e0d581366012/lib/core/loss.py#L40)

**Comment by jd0617** [comment]
Thank you so much for your fast reply!! ^^
